Repository WorkshopSEGroup/WorkshopProject, pull requests merged in 2020-06, with the labels that each got.

#165 Uc4.2 - Purchase Policy
  src/main/DomainLayer/StoreComponent/PurchasePolicy.py
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/main/ServiceLayer/GuestRole.py
  src/main/ServiceLayer/StoreOwnerOrManagerRole.py
  src/test/BlackBoxTests/AcceptanceTests/ProjectTest.py
  src/test/BlackBoxTests/AcceptanceTests/UcTests/DefineAndEditPolicies.py
  src/test/BlackBoxTests/Bridge/Bridge.py
  src/test/BlackBoxTests/Bridge/ProxyBridge.py
  src/test/BlackBoxTests/Bridge/RealBridge.py
Labels: Feature, Refactoring

#171 Finish 4.2 discount policy
  src/Logger.py
  src/main/DomainLayer/StoreComponent/DiscountPolicyComposite/CompositeFlag.py
  src/main/DomainLayer/StoreComponent/DiscountPolicyComposite/DiscountComponent.py
  src/main/DomainLayer/StoreComponent/DiscountPolicyComposite/DiscountPolicy.py
  src/main/DomainLayer/StoreComponent/DiscountPolicyComposite/Leaves/ConditionalDiscountPolicy.py
  src/main/DomainLayer/StoreComponent/DiscountPolicyComposite/Leaves/VisibleDiscountPolicy.py
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/main/DomainLayer/UserComponent/DiscountType.py
  src/main/ResponseFormat.py
  src/main/ServiceLayer/StoreOwnerOrManagerRole.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/StoreComponent/DiscountPolicyComposite/DiscountPolicyTests.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/StoreComponent/StoreTests.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/StoreOwnerOrManagerTests.py
Labels: Feature, MH, Refactoring

#175 Real time component
  .idea/WorkshopProject.iml
  src/main/CommunicationLayer/StorePublisher.py
  src/main/CommunicationLayer/WebService.py
  src/main/CommunicationLayer/WebSocketService.py
  src/main/CommunicationLayer/Websocket.py
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/main/DomainLayer/UserComponent/User.py
  src/main/DomainLayer/UserComponent/UserType.py
  src/main/PresentationLayer/RunServerScript.py
  src/main/PresentationLayer/package-lock.json
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/OwnerAPI.js
  src/main/PresentationLayer/src/components/SubscriberRole/OpenStore.js
  src/main/PresentationLayer/src/services/Notification_prev_try.js
  src/main/PresentationLayer/src/services/Notifications.js
  src/main/PresentationLayer/src/services/clientWebsocket.js
  src/main/ServiceLayer/GuestRole.py
  src/main/ServiceLayer/StoreOwnerOrManagerRole.py
  src/main/ServiceLayer/SubscriberRole.py
  src/main/ServiceLayer/TradeControlService.py
  src/main/main.py
  src/test/WhiteBoxTests/UnitTests/TestCases/CommunicationLayer/WebsocketTests.py
Labels: Feature, Refactoring

#192 added hashing passwords
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/main/DomainLayer/UserComponent/Registration.py
  src/main/DomainLayer/UserComponent/User.py
Labels: Feature, MH, Refactoring

#201 Refactoring v3
  src/main/CommunicationLayer/WebService.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/main/PresentationLayer/package.json
  src/main/PresentationLayer/src/App.css
  src/main/PresentationLayer/src/App.js
  src/main/PresentationLayer/src/components/Actions/ShoppingCartActions/PurchaseProducts.js
  src/main/PresentationLayer/src/components/GuestRole/Login.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/AppointOwner.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/AppointStoreManager.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/EditPermissions.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/ManagerAPI.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/Notifications.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/NotificationsActions.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/OwnerAPI.js
  src/main/PresentationLayer/src/components/SubscriberRole/OpenStore.js
  src/main/PresentationLayer/src/services/Notifications.js
  src/main/PresentationLayer/src/services/communication.js
Labels: Feature

#202 Uc 4.3
  src/main/CommunicationLayer/StorePublisher.py
  src/main/CommunicationLayer/WebService.py
  src/main/DomainLayer/StoreComponent/AppiontmentAgreement.py
  src/main/DomainLayer/StoreComponent/AppointmentStatus.py
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/main/DomainLayer/UserComponent/Login.py
  src/main/DomainLayer/UserComponent/User.py
  src/main/ServiceLayer/StoreOwnerOrManagerRole.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DomainLayer/StoreComponent/AppointmentAgreementTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DomainLayer/StoreComponent/StoreInventoryTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DomainLayer/StoreComponent/StoreTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DomainLayer/TradeComponent/TradeControlTestCase.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DomainLayer/UserComponent/UserTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/StoreOwnerOrManagerTests.py
Labels: Feature, MH, Refactoring

#203 Eytan's brunch2
  .gitignore
  src/Logger.py
  src/main/DataAccessLayer/ConnectionProxy/DbProxy.py
  src/main/DataAccessLayer/ConnectionProxy/DbSubject.py
  src/main/DataAccessLayer/ConnectionProxy/RealDb.py
  src/main/DataAccessLayer/ConnectionProxy/Tables.py
  src/main/DataAccessLayer/ConnectionProxy/testing.db
  src/main/DataAccessLayer/DataAccessFacade.py
  src/main/DataAccessLayer/StoreDataComponent/CompositeDiscountPolicyData.py
  src/main/DataAccessLayer/StoreDataComponent/ConditionalDiscountPolicyData.py
  src/main/DataAccessLayer/StoreDataComponent/DiscountPolicyData.py
  src/main/DataAccessLayer/StoreDataComponent/ProductData.py
  src/main/DataAccessLayer/StoreDataComponent/ProductsInPurchaseData.py
  src/main/DataAccessLayer/StoreDataComponent/PurchaseData.py
  src/main/DataAccessLayer/StoreDataComponent/StoreOwnerAppointmentData.py
  src/main/DataAccessLayer/UserDataComponent/ProductsInBasket.py
  src/main/DataAccessLayer/UserDataComponent/StatisticData.py
  src/main/DomainLayer/StoreComponent/DiscountPolicyComposite/Leaves/ConditionalDiscountPolicy.py
  src/main/ServiceLayer/TradeControlService.py
  src/main/ServiceLayer/init_sys_file_v3.txt
  src/main/ServiceLayer/init_sys_file_v4.txt
  src/test/WhiteBoxTests/IntegrationTests/DataAccessLayer/DataAccessFacadeTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DataAccessLayer/ConnectionProxy/DbProxyTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/TradeControlServiceTests.py
Labels: High-Risk, MH

#204 IMPORTANT TEST COMMIT!!!!!
  src/Logger.py
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/main/DomainLayer/UserComponent/Registration.py
  src/main/DomainLayer/UserComponent/User.py
  src/test/BlackBoxTests/BlackBoxTestsRunner.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/StoreComponent/StoreTests.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/TradeComponent/TradeControlTestCase.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/GuestRoleTests.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/StoreOwnerOrManagerTests.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/SubscriberRoleTests.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/SystemManagerRoleTests.py
  src/test/WhiteBoxTests/RegressionTests/RegressionTestsRunner.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DomainLayer/TradeComponent/TradeControlTestCase.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/GuestRoleTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/StoreOwnerOrManagerTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/SubscriberRoleTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/SystemManagerRoleTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/TradeControlServiceTests.py
  src/test/WhiteBoxTests/WhiteBoxTestsRunner.py
Labels: Feature, MH, Refactoring

#207 move the websocket login event from owner to subscriber
  src/main/CommunicationLayer/StorePublisher.py
  src/main/CommunicationLayer/WebService.py
  src/main/PresentationLayer/src/components/GuestRole/Login.js
  src/main/PresentationLayer/src/components/SubscriberRole/SubscriberAPI.js
  src/main/PresentationLayer/src/components/SystemManagerRole/SystemManagerAPI.js
Labels: High-Risk, MH

#210 Uc 4.3 solving bugs
  src/main/CommunicationLayer/StorePublisher.py
  src/main/CommunicationLayer/WebService.py
  src/main/DataAccessLayer/ConnectionProxy/testing.db-shm
  src/main/DataAccessLayer/ConnectionProxy/testing.db-wal
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/NotificationsActions.js
  src/main/PresentationLayer/src/services/Notifications.js
  src/main/main.py
Labels: Bug, Feature, MH, Refactoring

#212 4.3
  src/main/DataAccessLayer/UserDataComponent/StatisticData.py
Labels: Refactoring

#213 Parallel tests
  src/main/CommunicationLayer/WebService.py
  src/main/DataAccessLayer/DataAccessFacade.py
  src/main/DomainLayer/StoreComponent/Product.py
  src/main/DomainLayer/StoreComponent/Purchase.py
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/main/PresentationLayer/src/components/GuestRole/Login.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/ManagerAPI.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/OwnerAPI.js
  src/main/PresentationLayer/src/components/SubscriberRole/SubscriberAPI.js
  src/main/PresentationLayer/src/components/SystemManagerRole/SystemManagerAPI.js
  src/main/PresentationLayer/src/services/communication.js
  src/main/ServiceLayer/GuestRole.py
  src/main/ServiceLayer/StoreOwnerOrManagerRole.py
  src/main/ServiceLayer/SubscriberRole.py
  src/main/ServiceLayer/SystemManagerRole.py
  src/main/ServiceLayer/TradeControlService.py
  src/test/BlackBoxTests/AcceptanceTests/ProjectAT.py
  src/test/BlackBoxTests/AcceptanceTests/UcTests/AppointManagerTest.py
  src/test/BlackBoxTests/AcceptanceTests/UcTests/EditManagerPermissionsTest.py
  src/test/BlackBoxTests/AcceptanceTests/UcTests/InitSystemTest.py
  src/test/BlackBoxTests/AcceptanceTests/UcTests/LoginTest.py
  src/test/BlackBoxTests/AcceptanceTests/UcTests/LogoutTest.py
  src/test/BlackBoxTests/AcceptanceTests/UcTests/RemoveStoreOwner.py
  src/test/BlackBoxTests/AcceptanceTests/UcTests/ViewStoresAndUsersPurchaseHistoryTest.py
  src/test/BlackBoxTests/BlackBoxTestsRunner.py
  src/test/BlackBoxTests/Bridge/Bridge.py
  src/test/BlackBoxTests/Bridge/ProxyBridge.py
  src/test/BlackBoxTests/Bridge/RealBridge.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/StoreComponent/StoreInventoryTests.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/TradeComponent/TradeControlTestCase.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/GuestRoleTests.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/StoreOwnerOrManagerTests.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/SubscriberRoleTests.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/SystemManagerRoleTests.py
  src/test/WhiteBoxTests/ParallelTests/ParallelTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DomainLayer/TradeComponent/TradeControlTestCase.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/GuestRoleTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/StoreOwnerOrManagerTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/SubscriberRoleTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/SystemManagerRoleTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/ServiceLayer/TradeControlServiceTests.py
Labels: Feature, High-Risk

#214 Eytan's brunch2
  src/main/DataAccessLayer/ConnectionProxy/Tables.py
  src/main/DataAccessLayer/ConnectionProxy/testing.db
  src/main/DataAccessLayer/DataAccessFacade.py
  src/main/DataAccessLayer/StoreDataComponent/ProductsInPurchaseData.py
  src/main/DataAccessLayer/StoreDataComponent/StoreManagerAppointmentData.py
  src/main/DataAccessLayer/StoreDataComponent/StoreOwnerAppointmentData.py
  src/main/DomainLayer/StoreComponent/Purchase.py
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/test/WhiteBoxTests/IntegrationTests/DataAccessLayer/DataAccessFacadeTests.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/StoreComponent/StoreTests.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/TradeComponent/TradeControlTestCase.py
  src/test/WhiteBoxTests/IntegrationTests/ServiceLayer/StoreOwnerOrManagerTests.py
Labels: MH

#216 4.3 - IT tests
  src/main/CommunicationLayer/WebService.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/StoreComponent/AppointmentAgreementTests.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DomainLayer/StoreComponent/AppointmentAgreementTests.py
  src/test/WhiteBoxTests/WhiteBoxTestsRunner.py
Labels: Testing

#218 and some more minor fixes...
  src/main/CommunicationLayer/WebService.py
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/main/PresentationLayer/src/App.js
  src/main/PresentationLayer/src/components/Actions/ShoppingCartActions/PurchaseProducts.js
  src/main/PresentationLayer/src/components/GuestRole/Login.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/ManagerAPI.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/OwnerAPI.js
  src/main/PresentationLayer/src/components/OwnerOrManagerRole/StorePurchaseHistory.js
  src/main/PresentationLayer/src/components/SubscriberRole/SubscriberAPI.js
  src/main/PresentationLayer/src/components/SystemManagerRole/SystemManagerAPI.js
Labels: Refactoring, Testing

#222 4.3 for merge
  src/main/CommunicationLayer/WebService.py
  src/main/DataAccessLayer/ConnectionProxy/Tables.py
  src/main/DataAccessLayer/ConnectionProxy/testing.db
  src/main/DataAccessLayer/DataAccessFacade.py
  src/main/DataAccessLayer/StoreDataComponent/ProductsInPurchaseData.py
  src/main/DataAccessLayer/StoreDataComponent/StoreManagerAppointmentData.py
  src/main/DataAccessLayer/StoreDataComponent/StoreOwnerAppointmentData.py
  src/main/DomainLayer/StoreComponent/Purchase.py
  src/main/DomainLayer/StoreComponent/Store.py
  src/main/DomainLayer/TradeComponent/TradeControl.py
  src/test/WhiteBoxTests/IntegrationTests/DataAccessLayer/DataAccessFacadeTests.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/StoreComponent/AppointmentAgreementTests.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/StoreComponent/StoreTests.py
  src/test/WhiteBoxTests/IntegrationTests/DomainLayer/TradeComponent/TradeControlTestCase.py
  src/test/WhiteBoxTests/UnitTests/TestCases/DomainLayer/StoreComponent/AppointmentAgreementTests.py
  src/test/WhiteBoxTests/WhiteBoxTestsRunner.py
Labels: Refactoring
